# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
PINECONE_API_KEY = "pcsk_3A2FSq_PgLKDyokAP8n1GUQXX8SjZFUNoTxLnWojCqizjL67bE2qUBzJmyfbb4HkrxpwLu"
PINECONE_ENVIRONMENT = "us-east-1-aws"
